name: Matrix
on: pull_request

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [16, 18, 20]
        include:
          - os: ubuntu-latest
            node_version: 18
            is_ubuntu_18: "true"
        exclude:
          - os: ubuntu-latest
            node_version: 16
          - os: macos-latest
            node_version: 18
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_18: ${{ matrix.is_ubuntu_18 }}
    steps:
      - name: Log Node version
        run: node -v
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: |
          node -v
          echo $IS_UBUNTU_18
